### ISSUE TITLE
CoP PM 1-2 Below the Arks

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#14]
**5/26/2016 between 22:00-24:00**: 
**Everytime**:
**#0150508_8**:
**Baucant**:
**Elvann**:
**Thf**:
**Dnc**:
**Spire of Demx:0 y:-2 z:246 (63)**:
**Party**:
**Web of Recollections**:
**Monster Name**:
**never tried to reproduce the problem as i was tryinng to progress further in the mission. I have followed the quest exectly as told through the walk through, I spoke with Pherimociel and recieved CS, I spoke with Harith and mentions the emptyness. I did not recieve CS when entering Shatered telepoint, was teleported to Hall of Transferance, I used the Large Apparatus to enter promy. I climbed the promy for both Holla and Dem with the same result reaching the top and getting nowhere. This is also happening to my whm Mule Dapunted**:

**Comment by R3P0FFXI** [comment]
@addkeyitem 590/591/592 to Baucant and Dapunted

**Comment by R3P0FFXI** [comment]
Deletedmission 6 2 added mission 6 3

**Comment by TeoTwawki** [comment]
@R3P0FFXI just a reminder: make sure any temp vars (would be PromathiaStatus most likely) used during previous mission are wiped out before adding next mission.

**Comment by Baucant** [comment]
Attempted to continue my COP mission after R3p0 "interviened"still can not enter the battlefield.

**Comment by TeoTwawki** [comment]
He did the wrong thing. Will contact you in game to correct this mess.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/1487

**Comment by Baucant** [comment]
Thank you Teo I am able to continue my CoP adventure, fun, excitment!

**Comment by TeoTwawki** [comment]
Leaving issue open till its fixed in DSP. For next person that gets stuck:
```
@completemission 6 2 <t>
@addmission 6 3 <t>
```
And **do not** touch their KeyItems at all. The scritp for th battelfield is looking for their mission log to say "The Mothercrystals" and not already have the KI for that particular battlefield.

**Comment by gedads** [comment]
Got a fix ready but with too much things to test tonight, i'll add it tomorrow

**Comment by helixhamin** [comment]
My toons also need advanced...I am stuck at not being able to do the promy battles.

**Comment by KinoriGareth** [comment]
Hello~ God said to post in this existing one regarding the issue.

**Date & Time**: 5/29 - Roughly 10:00 AM to present
**Frequency**: Every time
**FFXI Client Version**: 30150508_8
**Character Name**: Kinori + Kinofloof
**Race**: Mithra
**Main Job**: RDM + WHM
**Sub Job**: SCH + RDM
**Area & Coordinates**: Spire of Dem/Mea (Not currently in there, can't get exact coords)
**Party or Solo**: Party
**NPC Name**: -
**Monster Name**: - 
**Steps To Reproduce The Issue**:

- Followed the CoP Mission guide on FFXI Wikia, making sure to get all cutscenes done for 1-1 + 1-2.
- Went to Promy-Dem, upon clicking the Shattered Telepoint and entering Hall of Transference, noticed I did not receive a cutscene like the wiki said I would, but I received one when clicking on the Large Apparatus, as well as when it transferred me into the Promy.
- Ran through normally, getting into the Spire of Dem
- Clicked on the Web of Recollections, but it just told me, "You can hear a faint scraping sound from within, but the way is barred by some strange membrane..."
- Tried going through Promy-Mea, to the same results.
- Backtraced all previous steps to double-check I was not missing any, including: Talking to Pherimociel, Harith, Monberaux, and zoning into Delkfutt's Tower. Also made sure of having the Key Item, Mysterious Amulet, from 1-1.
- Finally tried going through Promy-Dem one more time to see if talking to anyone did anything, to no avail.

**Comment by Tatako** [comment]
**Date & Time**: 5/31/15 / 5:00pm EST
**Frequency**: Every time
**FFXI Client Version**: 30150508_8
**Character Name**: Tatako
**Race**: Mithra
**Main Job**: SAM
**Sub Job**:DNC
**Area & Coordinates**: x:0 y:-2 z: -252 (196)  Spire of Holla
**Party or Solo**: Solo
**NPC Name**: n/a
**Monster Name**: n/a
**Steps To Reproduce The Issue**: As Baucant and Kinori

Followed the walkthrough, spoke with Pherimociel and recieved CS, I spoke with Harith and mentions the emptyness.  I do have mysterious amulet as temp key item.
I did not recieve CS when entering Shatered telepoint
Zoned into Hall of Transferance, I used the Large Apparatus (on left) to enter Dem and Holla. 
I climbed the promy for both Holla and Dem with the same result reaching the top and getting
the message:  "You can hear a faint scraping sound from within, but the way is barred by some strange membrane..."

You can zone back into Promy and fight things if needed.

**Comment by TeoTwawki** [comment]
*should* be fixed come Tuesdays maint, but @R3P0FFXI if you could run the commands on ppl in the meantime that'd be great. I have my hands full today.

**Comment by Tatako** [comment]
Thank you



On May 31, 2015, at 5:47 PM, TeoTwawki <notifications@github.com<mailto:notifications@github.com>> wrote:


should be fixed come Tuesdays maint, but @R3P0FFXI<https://github.com/R3P0FFXI> if you could run the commands on ppl in the meantime that'd be great. I have my hands full today.

-

**Comment by R3P0FFXI** [comment]
Commands have been run for Del;iade, Kinofloof, Yuehan, Weijun

**Comment by Tatako** [comment]
Did you miss Tatako?



On Jun 2, 2015, at 8:43 AM, R3P0FFXI <notifications@github.com<mailto:notifications@github.com>> wrote:


Commands have been run for Del;iade, Kinofloof, Yuehan, Weijun

-

**Comment by TeoTwawki** [comment]
He probably didn't notice the notification about your dupe issue. One of us will get you in the morning.

**Comment by R3P0FFXI** [comment]
Ran settings on Tatako but he appeared AFK

**Comment by Tatako** [comment]
I am thank you.

**Comment by R3P0FFXI** [comment]
Fixed Squall

**Comment by Squall-Bibi** [comment]
Not fixed for Squall and need fix for Bibi too please but, God i put me in 1-3 mothercrystal ok but now cant enter in all  3 promy (Shattered Telepoint no awnser me for enter for Squall)

----------------------------------------

Exactly same Kinori 

Date & Time: June 04
Frequency: Every time
FFXI Client Version: 30150508_8
Character Name: Bibi
Race: Htaru
Main Job: RDM
Sub Job: WHM
Area & Coordinates: Spire of Dem/Mea/Holla (not enter in Web of Recollections)
Party or Solo: Party and alone same
NPC Name: -
Monster Name: - 
Steps To Reproduce The Issue:

Followed the CoP Mission guide on FFXI Wikia, making sure to get all cutscenes done for 1-1 + 1-2.
Went to Promy-Dem-Mea or Dem, upon clicking the Shattered Telepoint and entering Hall of Transference, noticed I did not receive a cutscene like the wiki said I would, but I received one when clicking on the Large Apparatus, as well as when it transferred me into the Promy.
Ran through normally, getting into the Spire of Dem
Clicked on the Web of Recollections, but it just told me, "You can hear a faint scraping sound from within, but the way is barred by some strange membrane..."
Tried going through Promy-Mea, to the same results.
Backtraced all previous steps to double-check I was not missing any, including: Talking to Pherimociel, Harith, Monberaux, and zoning into Delkfutt's Tower. Also made sure of having the Key Item, Mysterious Amulet, from 1-1.
Finally tried going through Promy-Dem one more time to see if talking to anyone did anything, to no avail.

**Comment by R3P0FFXI** [comment]
This issue was resolved in last maint and has been tested by [GM], all CS work flawlessly if on the correct client.

**Comment by Squall-Bibi** [comment]
Don't works ... do you see my post ?

Player > Bibi stuck in PM 1-2 the cs after click on large apparatus again and again. and dont enter on the Web of Recollections.

Player > Squall (God put me in mothercrystals because stuck in PM1-2 same Bibi but other stuck) in PM 1-3 but don't access to promyvion no zone in shattered telepoint (the telepoint have been shattered in the thousand pieces) but not pop for enter.

**Comment by TeoTwawki** [comment]
I'll get you patched up in game. the issue sort of morphed because fixing it to work from start to finish still leaves ppl who were mid-mission barked by the change.

**Comment by Squall-Bibi** [comment]
Oh  you respond rapidly ! i open other ticket :) i need to open ticket for Squall ? not enter in promy zone in shattered telepoint ?

**Comment by TeoTwawki** [comment]
I'm in game trying to talk to your character lol
