### ISSUE TITLE
Leaping Lizzy / Rock Lizzard Spawning problem.

### ISSUE THREAD

**Issue by nxnslite** [LegionDark/Issues#1609]
**Date & Time**: 
2017-08-10 : 11:14am est

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170707_0

**Character Name**: 
Nxnslite

**Nation**: 
windurst

**Job(level)/Sub Job(level)**: 
not related

**NPC or Monster or item Name**: 
Leaping Lizzy / Rock Lizzard

**Zone name**: 
South Gustaberg

**Coordinates (use `$where`)**: 
around -324 30 -397

**ffxiah.com link (for items issues only)**: 
no related

**Multi-boxing? (multiple clients on same connection)**: 
no related

**Steps To Reproduce / any other info**: 
PH of leaping lizzy not spawing.
Instaed of the group of 5 (wich 1 is the PH) only the second 1 spawn 18C
might be related to old topic
NMs and PH not respawning #3663 https://github.com/DarkstarProject/darkstar/issues/3663
(problem): only one Rock Lizzard spawn on the hill where they normaly do.. and PH do not spawn at all.

**Comment by TeoTwawki** [comment]
the last lizzy if probably either stuck in bad action state or has wander through part of the map and can't get back.

I will log in later to check its state and see if I can un-stuck it. If map server restarts before then thats known to fix it before I can look. :(

**Comment by Raelious** [comment]
Checked back on this issue, all but 1 lizard are up and accounted for.
Will kill and see if LL does spawn or not.

**Comment by nxnslite** [comment]
I have not check on ll since the begening of the thread. It may have been fixed already. I didnt look at it.

**Comment by Raelious** [comment]
and its still broken. Killed the 9 PH's till LL spawned, killed LL. Now there are only 7 PHs left after 5 mins of killing LL.

Seems one of the other lizards are not spawning either, since there was 9 and now there are 7.

**Comment by TeoTwawki** [comment]
Sounds like a problem with `DeturMob()` but I really cannot check right now. My RL is busy. my mother has surgery in the morning. Torn rotator cuff, flesh detached from bone, I'm going to have to take care of her for awhile so ***It's gonna be awhile before anything in the game is a priority, unfortunately.***

Soon as I get free time (even when not caring for mom, I have some other higher priority work to handle) I will check on Leapin lizzy. All you guys can do for now is wait, capiche?

![calm young grasshop..er...fish...er..whatever](https://www.tenor.co/qvaX.gif )

**Comment by TeoTwawki** [comment]
Sounds like a problem with `DeturMob()` but I really cannot check right now. My RL is busy. my mother has surgery in the morning. Torn rotator cuff, flesh detached from bone, I'm going to have to take care of her for awhile so ***It's gonna be awhile before anything in the game is a priority, unfortunately.***

Soon as I get free time (even when not caring for mom, I have some other higher priority work to handle) I will check on Leapin lizzy. All you guys can do for now is wait, capiche?

![calm young grasshop..er...fish...er..whatever](https://media.tenor.com/images/85c874d39f319357872c22932f8afba9/tenor.gif)

**Comment by R3P0FFXI** [comment]
@nxnslite I believe this is finally being fixed by DSP, @TeoTwawki can confirm when the fix is in place

**Comment by TeoTwawki** [comment]
There is a mass replace of the lotto pop code ongoing. Which should take care of it once complete.
